// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/Admin/index.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/x/[Product].tsx";
import * as $$0 from "./islands/Cart.tsx";
import * as $$1 from "./islands/Footer.tsx";
import * as $$2 from "./islands/Settings.tsx";
import * as $$3 from "./islands/SettingsData.tsx";
import * as $$4 from "./islands/Wrap.tsx";

const manifest = {
  routes: {
    "./routes/Admin/index.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/x/[Product].tsx": $3,
  },
  islands: {
    "./islands/Cart.tsx": $$0,
    "./islands/Footer.tsx": $$1,
    "./islands/Settings.tsx": $$2,
    "./islands/SettingsData.tsx": $$3,
    "./islands/Wrap.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
